INSERT INTO tb_category (name) VALUES ('Entradas')
INSERT INTO tb_category (name) VALUES ('Porções')
INSERT INTO tb_category (name) VALUES ('Rápidos')
INSERT INTO tb_category (name) VALUES ('Executivos')
INSERT INTO tb_category (name) VALUES ('Especiais');
INSERT INTO tb_category (name) VALUES ('Sobremesas')
INSERT INTO tb_category (name) VALUES ('Bebidas')
INSERT INTO tb_category (name) VALUES ('Drinks')
INSERT INTO tb_category (name) VALUES ('Cervejas')
INSERT INTO tb_category (name) VALUES ('Vinhos')
INSERT INTO tb_category (name) VALUES ('Whiskies')

INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Porção de Azeitona', 'Azeitonas Verdes e Pretas - cod 101', 'Azeitonas Verdes e Pretas', 5.00, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Porção de Amendoim', 'Amendoins Torrados - cod 102', 'Azeitonas Verdes e Pretas', 5.00, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Torresmo de Barriguinha 250g', 'Torresmo de Barriguinha 250g com Molho Barbecue - cod 103', 'Torresmo de Barriguinha com molho Barbecue', 39.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Feijoada', 'Bolinho de Feijoada 6 unidades - cod 104', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Bacalhau', 'Bolinho de Bacalhau 4 unidades - cod 105', 'Bolinho de Bacalhau', 45.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Moqueca', 'Bolinho de Moqueca 6 unidades - cod 106', 'Bolinho de Moqueca', 45.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Carne', 'Bolinho de Carne 6 unidades - cod 107', 'Bolinho de Carne', 39.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Peixe', 'Bolinho de Peixe 6 unidades - cod 108', 'Bolinho de Peixe', 45.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Mix de Bolinhos', 'Bolinhos 2 de Carne, 2 de Feijoada, 2 de Moqueca e 2 de peixe - cod 109', 'Mix de Bolinhos', 54.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Pastelzinho Cabana', 'Pastelzinho Cabana 5 unidades - Carne ou Camarão - cod 110', 'Pastelzinho Cabana 5 unidades', 39.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Casquinha de Siri', 'Casquinha de Siri - 200G 1 unidades 1 unidade. Acompanha Farofa e Vinagrete - cod 111', 'Casquinha de Siri - 200G', 49.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Cascata de Camarao Medio', 'Cascata de Camarao Medio 6 unidades com molho tartaro - cod 112', 'Cascata de Camarao Medio', 59.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Linguica da Roça (Grossa) 250g', 'Linguica da Roca (Grossa) 250g com Queijo Coalho 100g - cod 113', 'Linguica da Roca (Grossa) 250g', 44.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Feijoada', 'Bolinho de Feijoada 6 unidades - cod 114', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 1)

INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('File de Pintado', 'File de Pintado (direto do Pantanal) 400g com Fritas - cod 301', 'File de Pintado com Fritas', 99.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Gurjão de peixe', 'Gurjão de peixe 400G com fritas - cod 302', 'Gurjão de peixe com fritas', 69.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Tilapia', 'Tilapia com fritas 400G - cod 303', 'Tilapia com fritas', 69.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Anéis de lula a doré', 'Anéis de lula a doré e molho tartaro - cod 304', 'Anéis de lula a doré', 59.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Manjubinha frita', 'Manjubinha frita 400G com molho e batatas fritas - cod 305', 'Manjubinha frita 400G', 59.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Filé de Linguado', 'Bolinho de Moqueca 6 unidades - cod 306', 'Bolinho de Moqueca', 45.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Mix de frutos do mar', 'Bolinho de Carne 6 unidades - cod 307', 'Bolinho de Carne', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Camarão maluquinho empanado', 'Bolinho de Peixe 6 unidades - cod 308', 'Bolinho de Peixe', 45.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Camarão VG empanado', 'Bolinhos 2 de Carne, 2 de Feijoada, 2 de Moqueca e 2 de peixe - cod 309', 'Mix de Bolinhos', 54.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Peroá simples', 'Pastelzinho Cabana 5 unidades - Carne ou Camarão - cod 310', 'Pastelzinho Cabana 5 unidades', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Peroá completo', 'Casquinha de Siri - 200G 1 unidades 1 unidade. Acompanha Farofa e Vinagrete - cod 311', 'Casquinha de Siri - 200G', 49.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Peroá super completo', 'Cascata de Camarao Medio 6 unidades com molho tartaro - cod 312', 'Cascata de Camarao Medio', 59.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Batata frita simples', 'Linguica da Roca (Grossa) 250g com Queijo Coalho 100g - cod 313', 'Linguica da Roca (Grossa) 250g', 44.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Batata frita especial', 'Bolinho de Feijoada 6 unidades - cod 314', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Aipim frito', 'Bolinho de Feijoada 6 unidades - cod 315', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Filé mignon acebolado na manteiga', 'Bolinho de Feijoada 6 unidades - cod 316', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Carne do Sol acebolado na manteiga', 'Bolinho de Feijoada 6 unidades - cod 317', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Costela bovina ao queijo', 'Bolinho de Feijoada 6 unidades - cod 318', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Frango a passarinho', 'Bolinho de Feijoada 6 unidades - cod 319', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Kieber de frango', 'Bolinho de Feijoada 6 unidades - cod 320', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Costelinha suína grelhada', 'Bolinho de Feijoada 6 unidades - cod 321', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Torresmo', 'Bolinho de Feijoada 6 unidades - cod 322', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 2)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Linguiça caseira', 'Bolinho de Feijoada 6 unidades - cod 323', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 2)
