INSERT INTO tb_category (name) VALUES ('Entradas')
INSERT INTO tb_category (name) VALUES ('Porções')
INSERT INTO tb_category (name) VALUES ('Rápidos')
INSERT INTO tb_category (name) VALUES ('Executivos')
INSERT INTO tb_category (name) VALUES ('Especiais');
INSERT INTO tb_category (name) VALUES ('Sobremesas')
INSERT INTO tb_category (name) VALUES ('Bebidas')
INSERT INTO tb_category (name) VALUES ('Drinks')
INSERT INTO tb_category (name) VALUES ('Cervejas')
INSERT INTO tb_category (name) VALUES ('Vinhos')
INSERT INTO tb_category (name) VALUES ('Whiskies')

INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Porção de Azeitona', 'Azeitonas Verdes e Pretas - cod 101', 'Azeitonas Verdes e Pretas', 5.00, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Porção de Amendoim', 'Amendoins Torrados - cod 102', 'Azeitonas Verdes e Pretas', 5.00, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Torresmo de Barriguinha 250g', 'Torresmo de Barriguinha 250g com Molho Barbecue - cod 103', 'Torresmo de Barriguinha com molho Barbecue', 39.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Feijoada', 'Bolinho de Feijoada 6 unidades - cod 104', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Bacalhau', 'Bolinho de Bacalhau 4 unidades - cod 105', 'Bolinho de Bacalhau', 45.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Moqueca', 'Bolinho de Moqueca 6 unidades - cod 106', 'Bolinho de Moqueca', 45.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Carne', 'Bolinho de Carne 6 unidades - cod 107', 'Bolinho de Carne', 39.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Peixe', 'Bolinho de Peixe 6 unidades - cod 108', 'Bolinho de Peixe', 45.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Mix de Bolinhos', 'Bolinhos 2 de Carne, 2 de Feijoada, 2 de Moqueca e 2 de peixe - cod 109', 'Mix de Bolinhos', 54.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Pastelzinho Cabana', 'Pastelzinho Cabana 5 unidades - Carne ou Camarão - cod 110', 'Pastelzinho Cabana 5 unidades', 39.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Casquinha de Siri', 'Casquinha de Siri - 200G 1 unidades 1 unidade. Acompanha Farofa e Vinagrete - cod 111', 'Casquinha de Siri - 200G', 49.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Cascata de Camarao Medio', 'Cascata de Camarao Medio 6 unidades com molho tartaro - cod 112', 'Cascata de Camarao Medio', 59.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Linguica da Roça (Grossa) 250g', 'Linguica da Roca (Grossa) 250g com Queijo Coalho 100g - cod 113', 'Linguica da Roca (Grossa) 250g', 44.90, 'Valor da Imagem URL', NOW(), 1)
INSERT INTO TB_PRODUCT (name, description, short_Description, price, img_Url, date, category_id) VALUES ('Bolinho de Feijoada', 'Bolinho de Feijoada 6 unidades - cod 114', 'Bolinho de Feijoada', 39.90, 'Valor da Imagem URL', NOW(), 1)
